.github/workflows/release-please.yaml
Reinstates https://github.com/netlify/primitives/pull/151 (temporarily removed in https://github.com/netlify/primitives/pull/159) now that the repository is public.
=> chore: add back npm provenance

packages/cache/package.json
Fixes the failure in https://github.com/netlify/primitives/actions/runs/14886703492/job/41808114525#step:13:74.
=> chore: fix repo name in README

package-lock.json, packages/dev/package.json, packages/dev/src/main.ts, packages/functions/dev/builder.ts, packages/functions/dev/function.ts, packages/functions/dev/main.ts, packages/functions/dev/registry.ts, packages/functions/dev/runtimes/index.ts, packages/functions/dev/runtimes/nodejs/builder.ts, packages/functions/dev/runtimes/nodejs/index.ts, packages/functions/package.json
I noticed that I would get errors in functions when using the Vite plugin and making multiple requests to the same function. I realised that this is because, unlike the CLI, in the Vite plugin we're not watching files for changes. We're just calling the `handle()` function on requests and that will cause functions to be built with the latest state of their source files.
In practice, this meant that we could have multiple function builders writing to the `.netlify/functions-serve` directory, which was breaking things. 
This PR introduces two changes:
1. We stop building all functions automatically, and instead we lazily build only the function that matches the incoming request
2. We make each function builder write to an ephemeral directory inside `.netlify/functions-serve`, so that …
=> fix: use ephemeral directories to serve functions

package-lock.json, packages/dev/package.json, packages/functions/package.json
Pins the version of `@netlify/blobs` in the `dev` and `functions` packages.
=> fix: pin monorepo packages

packages/blobs/package.json, packages/cache/package.json, packages/functions/package.json, packages/otel/package.json
Most of this monorepo's packages test scripts had consistent behaviour except these few.
This also resulted in the documented `npm run test -ws` hanging because some of the packages' `test` commands were watching for changes.
=> build: fix vitest scripts

packages/edge-functions/dev/deno/server.mjs, packages/edge-functions/dev/node/main.ts
I don't know why this works locally but not when pulling the code from the npm package, but it seems that passing parameters to the Deno script via its import URL is causing issues.
This PR changes it so that the run options are passed via `Deno.args`.
=> fix: pass run options to Deno script as arg

packages/dev/src/main.test.ts, packages/functions/dev/main.test.ts, packages/functions/dev/runtimes/nodejs/lambda.ts
Without this check, sending to the functions handler a request with query parameters in the URL would fail.
=> fix: add guard against query param handling

package-lock.json, packages/otel/package.json
this is the last package downgrade we need to support node 18.14 for netlify/otel
=> fix: bring back node 18.14 support by using older version of the @opentelemetry/otlp-transformer package

packages/blobs/src/client.ts, packages/blobs/src/main.test.ts, packages/blobs/src/store.ts
Adds support for conditional writes to Netlify Blobs by introducing two new options in the `set` and `setJSON` methods:
- `onlyIfNew` (boolean): When set, the write succeeds only if there isn't already an entry with the given key
- `onlyIfMatch` (string): When set, the write succeeds only if there is already an entry with the given key and with an ETag matching this value
By default, `set` and `setJSON` are upsert operations, which means that they will update any existing entry with the new value if one exists, or otherwise create a new one. The new options make it possible to customise that behaviour.
`onlyIfNew` lets you perform a create-only operation, making `set` and `setJSON` a no-op if the key already exists.
**✅ Atomic operation**
```ts
const store = getStore("countries")
// Store …
```
=> feat!: add support for conditional writes

packages/dev/src/main.ts, packages/edge-functions/dev/node/main.test.ts, packages/edge-functions/dev/node/main.ts, packages/images/src/main.test.ts, packages/images/src/main.ts, packages/vite-plugin/src/main.test.ts, packages/vite-plugin/src/main.ts
Currently, `NetlifyDev` accepts a `serverAddress` option in the constructor. When used in the Vite plugin, this property needs to match the address of the Vite server. This is a problem in some Vite-based frameworks (like Astro), because when we initialise the plugin, the server isn't running yet, so we don't know what port it uses.
With this PR, we're able to defer the definition of `serverAddress` to the `handle` method. At that point, we know for a fact that the Vite server is already running, so we grab the port and set it on the `handle` options.
I have kept the `serverAddress` option in the constructor for backwards-compatibility; if both are supplied, the one in `handle` takes precedence.
=> feat: add `serverAddress` to request handler

packages/blobs/src/server.ts, packages/vite-plugin/src/main.ts
relates to https://github.com/withastro/astro/pull/13768
two commits:
1. Use the target directory to store temp files (because `fs.rename` creates a hard link, so if the tmpdir is not on the same volume as the code this will fail -- happens in windows builds)
2. Be more defensive about how we create and destroy the dev server in the vite plugin -- `closeBundle` can run multiple times, and as closely related to dev server lifecycle as the httpServer "close" event
=> fix: apply fixes required for Vite plugin in Astro 

package-lock.json, packages/nuxt-module/package.json, packages/nuxt-module/src/module.ts, packages/nuxt-module/test/fixtures/with-functions/nuxt.config.ts
The current approach worked with nuxt 3 and nuxt 3 with `compatibilityVersion: 4`, but not actual nuxt 4 releases, for some reason.
This is the documented, canonical way, and it works with all versions!
---
Co-authored-by: Daniel Roe <daniel@roe.dev>
=> fix: use documented nuxt dev server url to fix nuxt 4 bug

packages/edge-functions/dev/node/main.test.ts, packages/edge-functions/dev/node/main.ts, packages/edge-functions/src/lib/config.ts
Closes https://linear.app/netlify/issue/RUN-1783/add-edge-function-matching-by-header-to-primitives-monorepo.
=> feat: support header matching in edge functions

package-lock.json, packages/functions/package.json, packages/functions/src/function/v2.ts
Exports `Context` type from `@netlify/types` and removes dependency on `@netlify/serverless-functions-api`.
Closes https://github.com/netlify/primitives/issues/302.
=> fix: export `Context` type from `@netlify/types`

packages/nuxt-module/test/basic.test.ts, packages/nuxt-module/test/functions.test.ts
The nuxt module tests run the module in dev mode (because that's the point of our nuxt module), which results in HMR being enabled. Unlike the main vite port, there's no dynamic port selection for the HMR WebSocket port, so when the test files run in parallel they often conflict by trying to bind to the same port.
I could harcode two different ports with `vite.server.hmr.port`, but there's very little value to exercising the HMR code path with these tests, so I just disabled it.
See very similar [Astro testing issue](https://github.com/withastro/astro/pull/11744) similarly resolved by https://github.com/vitejs/vite/pull/16219.
=> chore: fix `@netlify/nuxt` flakes due to HMR port conflict

packages/blobs/src/environment.ts, packages/cache/src/fetchwithcache.ts, packages/edge-functions/src/main.ts, packages/runtime/src/lib/globals.ts
I did a bunch of research on this and I'm fairly confident it's a bug, but I couldn't come up with a minimal repro to open an issue and felt like I couldn't justify spending more time here.
This is a valuable rule, so I'd rather not suppress on this line or globally.
Splitting into two lines resolves it and that seems totally fine, especially with a comment 🤷🏼.
=> chore: fix outstanding eslint errors

.github/CODEOWNERS
See https://github.com/netlify/primitives/pull/376 making changes to files in `packages/nuxt-module/test/` and review being requested from runtime team where it should be frameworks
Also per https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax our current syntax matches this example:
```
docs/* docs@example.com
```
I'm not sure proposed change is fully correct, just that current one doesn't seem correct
=> chore: update CODEOWNERS to match all nested paths

package-lock.json, packages/vite-plugin/package.json
We no longer use this in the vite-plugin package, so it should be safe to remove.
=> fix(deps): remove unused chalk dependency

package-lock.json, package.json
We pull our lint rules from the root `typescript-eslint` 'mono package' now, so don't need to pull the plugin in directly anymore.
=> chore: drop unused TSESLint dependency

eslint_temporary_suppressions.js, packages/otel/src/bootstrap/main.ts, packages/otel/src/exporters/netlify.ts, packages/otel/src/instrumentations/fetch.ts, packages/otel/tsup.config.ts
Some basic fetch instrumentation. It works!
Once it's been in context a little perhaps we'd like to flesh it out by also instrumenting `"node:http"` and `"node:https"`
=> Add a minimal fetch instrumentation

packages/dev/src/lib/env.ts
Related issue: https://github.com/netlify/cli/pull/7585
=> fix(dev): add support for `dev-server` context

packages/cache/src/cache-headers/cache-headers.test.ts, packages/cache/src/main.ts
Exports the `cacheHeaders` method that returns a set of cache headers based on the settings supplied.
_Example_
```ts
import { cacheHeaders, DAY } from "@netlify/cache"
export default async () => new Response("I shall be cached", {
headers: {
...cacheHeaders({
ttl: 2 * DAY, // Two days
tags: ["product", "sale"],
vary: {
cookie: ["ab_test_name", "ab_test_bucket"],
query: ["item_id", "page"]
}
})
}
})
```
=> feat: export `cacheHeaders` method

packages/vite-plugin-tanstack-start/test/support/netlify-deploy.ts
See https://github.com/netlify/primitives/actions/runs/17913287769/job/50929548605?pr=456#step:12:771 - the setup as is failing on release PRs when package versions are bumped in repo, but were not published to npm yet
=> test: fix tanstack e2e test setup
